//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    
    public class ActivityStatsResponseDto
    {

        [JsonProperty("weeklySent")]
        public double WeeklySent { get; set; } = default!;

        [JsonProperty("monthlySent")]
        public double MonthlySent { get; set; } = default!;
    }
}