//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class AddSubscribersRequestDto
    {

        /// <summary>
        /// List of subscriber identifiers that will be associated to the topic
        /// </summary>
        [JsonProperty("subscribers")]
        public List<string> Subscribers { get; set; } = default!;
    }
}