//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Novu.Utils;

    /// <summary>
    /// Parsed JSON body from the agent webhook response when JSON.
    /// </summary>
    public class AgentReply
    {
    }
}