//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class BulkUpdateSubscriberPreferencesDtoContextType
    {
        private BulkUpdateSubscriberPreferencesDtoContextType(string value) { Value = value; }

        public string Value { get; private set; }

        public static BulkUpdateSubscriberPreferencesDtoContextType Str { get { return new BulkUpdateSubscriberPreferencesDtoContextType("str"); } }

        public static BulkUpdateSubscriberPreferencesDtoContextType Context2 { get { return new BulkUpdateSubscriberPreferencesDtoContextType("context_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(BulkUpdateSubscriberPreferencesDtoContextType v) { return v.Value; }
        public static BulkUpdateSubscriberPreferencesDtoContextType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "context_2": return Context2;
                default: throw new ArgumentException("Invalid value for BulkUpdateSubscriberPreferencesDtoContextType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((BulkUpdateSubscriberPreferencesDtoContextType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(BulkUpdateSubscriberPreferencesDtoContext.BulkUpdateSubscriberPreferencesDtoContextConverter))]
    public class BulkUpdateSubscriberPreferencesDtoContext
    {
        public BulkUpdateSubscriberPreferencesDtoContext(BulkUpdateSubscriberPreferencesDtoContextType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Context2? Context2 { get; set; }

        public BulkUpdateSubscriberPreferencesDtoContextType Type { get; set; }
        public static BulkUpdateSubscriberPreferencesDtoContext CreateStr(string str)
        {
            BulkUpdateSubscriberPreferencesDtoContextType typ = BulkUpdateSubscriberPreferencesDtoContextType.Str;

            BulkUpdateSubscriberPreferencesDtoContext res = new BulkUpdateSubscriberPreferencesDtoContext(typ);
            res.Str = str;
            return res;
        }
        public static BulkUpdateSubscriberPreferencesDtoContext CreateContext2(Context2 context2)
        {
            BulkUpdateSubscriberPreferencesDtoContextType typ = BulkUpdateSubscriberPreferencesDtoContextType.Context2;

            BulkUpdateSubscriberPreferencesDtoContext res = new BulkUpdateSubscriberPreferencesDtoContext(typ);
            res.Context2 = context2;
            return res;
        }

        public class BulkUpdateSubscriberPreferencesDtoContextConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(BulkUpdateSubscriberPreferencesDtoContext);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new BulkUpdateSubscriberPreferencesDtoContext(BulkUpdateSubscriberPreferencesDtoContextType.Context2)
                    {
                        Context2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Context2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Context2), new BulkUpdateSubscriberPreferencesDtoContext(BulkUpdateSubscriberPreferencesDtoContextType.Context2), "Context2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new BulkUpdateSubscriberPreferencesDtoContext(BulkUpdateSubscriberPreferencesDtoContextType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                BulkUpdateSubscriberPreferencesDtoContext res = (BulkUpdateSubscriberPreferencesDtoContext)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Context2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Context2));
                    return;
                }
            }

        }

    }
}