//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class ChannelCredentials
    {

        /// <summary>
        /// Webhook URL used by chat app integrations. The webhook should be obtained from the chat app provider.
        /// </summary>
        [JsonProperty("webhookUrl")]
        public string? WebhookUrl { get; set; }

        /// <summary>
        /// Channel specification for Mattermost chat notifications.
        /// </summary>
        [JsonProperty("channel")]
        public string? Channel { get; set; }

        /// <summary>
        /// Contains an array of the subscriber device tokens for a given provider. Used on Push integrations.
        /// </summary>
        [JsonProperty("deviceTokens")]
        public List<string>? DeviceTokens { get; set; }

        /// <summary>
        /// Alert UID for Grafana on-call webhook payload.
        /// </summary>
        [JsonProperty("alertUid")]
        public string? AlertUid { get; set; }

        /// <summary>
        /// Title to be used with Grafana on-call webhook.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Image URL property for Grafana on-call webhook.
        /// </summary>
        [JsonProperty("imageUrl")]
        public string? ImageUrl { get; set; }

        /// <summary>
        /// State property for Grafana on-call webhook.
        /// </summary>
        [JsonProperty("state")]
        public string? State { get; set; }

        /// <summary>
        /// Link to upstream details property for Grafana on-call webhook.
        /// </summary>
        [JsonProperty("externalUrl")]
        public string? ExternalUrl { get; set; }
    }
}