//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ContentType
    {
        private ContentType(string value) { Value = value; }

        public string Value { get; private set; }

        public static ContentType MarkdownReplyContentDto { get { return new ContentType("MarkdownReplyContentDto"); } }

        public static ContentType CardReplyContentDto { get { return new ContentType("CardReplyContentDto"); } }

        public static ContentType ToolApprovalCardReplyContentDto { get { return new ContentType("ToolApprovalCardReplyContentDto"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ContentType v) { return v.Value; }
        public static ContentType FromString(string v) {
            switch(v) {
                case "MarkdownReplyContentDto": return MarkdownReplyContentDto;
                case "CardReplyContentDto": return CardReplyContentDto;
                case "ToolApprovalCardReplyContentDto": return ToolApprovalCardReplyContentDto;
                default: throw new ArgumentException("Invalid value for ContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Replacement content. Exactly one of markdown, card, or toolApprovalCard.
    /// </summary>
    [JsonConverter(typeof(Content.ContentConverter))]
    public class Content
    {
        public Content(ContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public MarkdownReplyContentDto? MarkdownReplyContentDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CardReplyContentDto? CardReplyContentDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public ToolApprovalCardReplyContentDto? ToolApprovalCardReplyContentDto { get; set; }

        public ContentType Type { get; set; }
        public static Content CreateMarkdownReplyContentDto(MarkdownReplyContentDto markdownReplyContentDto)
        {
            ContentType typ = ContentType.MarkdownReplyContentDto;

            Content res = new Content(typ);
            res.MarkdownReplyContentDto = markdownReplyContentDto;
            return res;
        }
        public static Content CreateCardReplyContentDto(CardReplyContentDto cardReplyContentDto)
        {
            ContentType typ = ContentType.CardReplyContentDto;

            Content res = new Content(typ);
            res.CardReplyContentDto = cardReplyContentDto;
            return res;
        }
        public static Content CreateToolApprovalCardReplyContentDto(ToolApprovalCardReplyContentDto toolApprovalCardReplyContentDto)
        {
            ContentType typ = ContentType.ToolApprovalCardReplyContentDto;

            Content res = new Content(typ);
            res.ToolApprovalCardReplyContentDto = toolApprovalCardReplyContentDto;
            return res;
        }

        public class ContentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Content);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Content(ContentType.MarkdownReplyContentDto)
                    {
                        MarkdownReplyContentDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<MarkdownReplyContentDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(MarkdownReplyContentDto), new Content(ContentType.MarkdownReplyContentDto), "MarkdownReplyContentDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Content(ContentType.CardReplyContentDto)
                    {
                        CardReplyContentDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CardReplyContentDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CardReplyContentDto), new Content(ContentType.CardReplyContentDto), "CardReplyContentDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Content(ContentType.ToolApprovalCardReplyContentDto)
                    {
                        ToolApprovalCardReplyContentDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<ToolApprovalCardReplyContentDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(ToolApprovalCardReplyContentDto), new Content(ContentType.ToolApprovalCardReplyContentDto), "ToolApprovalCardReplyContentDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Content res = (Content)value;

                if (res.MarkdownReplyContentDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MarkdownReplyContentDto));
                    return;
                }

                if (res.CardReplyContentDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CardReplyContentDto));
                    return;
                }

                if (res.ToolApprovalCardReplyContentDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ToolApprovalCardReplyContentDto));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}