//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateTopicSubscriptionsRequestDtoContextType
    {
        private CreateTopicSubscriptionsRequestDtoContextType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CreateTopicSubscriptionsRequestDtoContextType Str { get { return new CreateTopicSubscriptionsRequestDtoContextType("str"); } }

        public static CreateTopicSubscriptionsRequestDtoContextType CreateTopicSubscriptionsRequestDtoContext2 { get { return new CreateTopicSubscriptionsRequestDtoContextType("CreateTopicSubscriptionsRequestDto_context_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateTopicSubscriptionsRequestDtoContextType v) { return v.Value; }
        public static CreateTopicSubscriptionsRequestDtoContextType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "CreateTopicSubscriptionsRequestDto_context_2": return CreateTopicSubscriptionsRequestDtoContext2;
                default: throw new ArgumentException("Invalid value for CreateTopicSubscriptionsRequestDtoContextType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateTopicSubscriptionsRequestDtoContextType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(CreateTopicSubscriptionsRequestDtoContext.CreateTopicSubscriptionsRequestDtoContextConverter))]
    public class CreateTopicSubscriptionsRequestDtoContext
    {
        public CreateTopicSubscriptionsRequestDtoContext(CreateTopicSubscriptionsRequestDtoContextType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CreateTopicSubscriptionsRequestDtoContext2? CreateTopicSubscriptionsRequestDtoContext2 { get; set; }

        public CreateTopicSubscriptionsRequestDtoContextType Type { get; set; }
        public static CreateTopicSubscriptionsRequestDtoContext CreateStr(string str)
        {
            CreateTopicSubscriptionsRequestDtoContextType typ = CreateTopicSubscriptionsRequestDtoContextType.Str;

            CreateTopicSubscriptionsRequestDtoContext res = new CreateTopicSubscriptionsRequestDtoContext(typ);
            res.Str = str;
            return res;
        }
        public static CreateTopicSubscriptionsRequestDtoContext CreateCreateTopicSubscriptionsRequestDtoContext2(CreateTopicSubscriptionsRequestDtoContext2 createTopicSubscriptionsRequestDtoContext2)
        {
            CreateTopicSubscriptionsRequestDtoContextType typ = CreateTopicSubscriptionsRequestDtoContextType.CreateTopicSubscriptionsRequestDtoContext2;

            CreateTopicSubscriptionsRequestDtoContext res = new CreateTopicSubscriptionsRequestDtoContext(typ);
            res.CreateTopicSubscriptionsRequestDtoContext2 = createTopicSubscriptionsRequestDtoContext2;
            return res;
        }

        public class CreateTopicSubscriptionsRequestDtoContextConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateTopicSubscriptionsRequestDtoContext);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CreateTopicSubscriptionsRequestDtoContext(CreateTopicSubscriptionsRequestDtoContextType.CreateTopicSubscriptionsRequestDtoContext2)
                    {
                        CreateTopicSubscriptionsRequestDtoContext2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CreateTopicSubscriptionsRequestDtoContext2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CreateTopicSubscriptionsRequestDtoContext2), new CreateTopicSubscriptionsRequestDtoContext(CreateTopicSubscriptionsRequestDtoContextType.CreateTopicSubscriptionsRequestDtoContext2), "CreateTopicSubscriptionsRequestDtoContext2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new CreateTopicSubscriptionsRequestDtoContext(CreateTopicSubscriptionsRequestDtoContextType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateTopicSubscriptionsRequestDtoContext res = (CreateTopicSubscriptionsRequestDtoContext)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.CreateTopicSubscriptionsRequestDtoContext2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreateTopicSubscriptionsRequestDtoContext2));
                    return;
                }
            }

        }

    }
}