//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// Rich context object with id and optional data.
    /// </summary>
    public class CreateSlackChannelEndpointDtoContext2
    {
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Optional additional context data.
        /// </summary>
        [JsonProperty("data")]
        public Dictionary<string, object>? Data { get; set; }
    }
}