//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;

    public class CreatedSubscriberDto
    {
        /// <summary>
        /// The ID of the subscriber that was created.
        /// </summary>
        [JsonProperty("subscriberId")]
        public string SubscriberId { get; set; } = default!;
    }
}