//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    
    public class CreateTopicRequestDto
    {

        /// <summary>
        /// User defined custom key and provided by the user that will be an unique identifier for the Topic created.
        /// </summary>
        [JsonProperty("key")]
        public string Key { get; set; } = default!;

        /// <summary>
        /// User defined custom name and provided by the user that will name the Topic created.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;
    }
}