//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class CreateTopicSubscriptionsRequestDto
    {

        /// <summary>
        /// List of subscriber identifiers to subscribe to the topic (max: 100)
        /// </summary>
        [JsonProperty("subscriberIds")]
        public List<string> SubscriberIds { get; set; } = default!;
    }
}