//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CreateWebexRoomEndpointDtoContextType
    {
        private CreateWebexRoomEndpointDtoContextType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CreateWebexRoomEndpointDtoContextType Str { get { return new CreateWebexRoomEndpointDtoContextType("str"); } }

        public static CreateWebexRoomEndpointDtoContextType CreateWebexRoomEndpointDtoContext2 { get { return new CreateWebexRoomEndpointDtoContextType("CreateWebexRoomEndpointDto_context_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateWebexRoomEndpointDtoContextType v) { return v.Value; }
        public static CreateWebexRoomEndpointDtoContextType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "CreateWebexRoomEndpointDto_context_2": return CreateWebexRoomEndpointDtoContext2;
                default: throw new ArgumentException("Invalid value for CreateWebexRoomEndpointDtoContextType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateWebexRoomEndpointDtoContextType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(CreateWebexRoomEndpointDtoContext.CreateWebexRoomEndpointDtoContextConverter))]
    public class CreateWebexRoomEndpointDtoContext
    {
        public CreateWebexRoomEndpointDtoContext(CreateWebexRoomEndpointDtoContextType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public CreateWebexRoomEndpointDtoContext2? CreateWebexRoomEndpointDtoContext2 { get; set; }

        public CreateWebexRoomEndpointDtoContextType Type { get; set; }
        public static CreateWebexRoomEndpointDtoContext CreateStr(string str)
        {
            CreateWebexRoomEndpointDtoContextType typ = CreateWebexRoomEndpointDtoContextType.Str;

            CreateWebexRoomEndpointDtoContext res = new CreateWebexRoomEndpointDtoContext(typ);
            res.Str = str;
            return res;
        }
        public static CreateWebexRoomEndpointDtoContext CreateCreateWebexRoomEndpointDtoContext2(CreateWebexRoomEndpointDtoContext2 createWebexRoomEndpointDtoContext2)
        {
            CreateWebexRoomEndpointDtoContextType typ = CreateWebexRoomEndpointDtoContextType.CreateWebexRoomEndpointDtoContext2;

            CreateWebexRoomEndpointDtoContext res = new CreateWebexRoomEndpointDtoContext(typ);
            res.CreateWebexRoomEndpointDtoContext2 = createWebexRoomEndpointDtoContext2;
            return res;
        }

        public class CreateWebexRoomEndpointDtoContextConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateWebexRoomEndpointDtoContext);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CreateWebexRoomEndpointDtoContext(CreateWebexRoomEndpointDtoContextType.CreateWebexRoomEndpointDtoContext2)
                    {
                        CreateWebexRoomEndpointDtoContext2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<CreateWebexRoomEndpointDtoContext2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(CreateWebexRoomEndpointDtoContext2), new CreateWebexRoomEndpointDtoContext(CreateWebexRoomEndpointDtoContextType.CreateWebexRoomEndpointDtoContext2), "CreateWebexRoomEndpointDtoContext2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new CreateWebexRoomEndpointDtoContext(CreateWebexRoomEndpointDtoContextType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CreateWebexRoomEndpointDtoContext res = (CreateWebexRoomEndpointDtoContext)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.CreateWebexRoomEndpointDtoContext2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CreateWebexRoomEndpointDtoContext2));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}