//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class CreateMsTeamsChannelEndpointDto
    {
        /// <summary>
        /// The unique identifier for the channel endpoint. If not provided, one will be generated automatically.
        /// </summary>
        [JsonProperty("identifier")]
        public string? Identifier { get; set; }

        /// <summary>
        /// The subscriber ID to which the channel endpoint is linked.
        /// </summary>
        [JsonProperty("subscriberId")]
        public string SubscriberId { get; set; } = default!;

        [JsonProperty("context")]
        public Dictionary<string, CreateMsTeamsChannelEndpointDtoContext>? Context { get; set; }

        /// <summary>
        /// The identifier of the integration to use for this channel endpoint.
        /// </summary>
        [JsonProperty("integrationIdentifier")]
        public string IntegrationIdentifier { get; set; } = default!;

        /// <summary>
        /// The identifier of the channel connection to use for this channel endpoint.
        /// </summary>
        [JsonProperty("connectionIdentifier")]
        public string? ConnectionIdentifier { get; set; }

        /// <summary>
        /// Type of channel endpoint.
        /// </summary>
        [JsonProperty("type")]
        public CreateMsTeamsChannelEndpointDtoType Type { get; set; } = default!;

        /// <summary>
        /// MS Teams channel endpoint data.
        /// </summary>
        [JsonProperty("endpoint")]
        public MsTeamsChannelEndpointDto Endpoint { get; set; } = default!;
    }
}