//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;
    
    /// <summary>
    /// Type of the delay. Currently only &apos;regular&apos; is supported by the schema.
    /// </summary>
    public enum DelayStepResponseDtoType
    {
        [JsonProperty("regular")]
        Regular,
        [JsonProperty("timed")]
        Timed,
    }

    public static class DelayStepResponseDtoTypeExtension
    {
        public static string Value(this DelayStepResponseDtoType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DelayStepResponseDtoType ToEnum(this string value)
        {
            foreach(var field in typeof(DelayStepResponseDtoType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DelayStepResponseDtoType)
                    {
                        return (DelayStepResponseDtoType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DelayStepResponseDtoType");
        }
    }

}