//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;

    public class DeleteMessagePayloadDto
    {
        /// <summary>
        /// Platform message id to delete. Removes the rendered message only — history is preserved.
        /// </summary>
        [JsonProperty("messageId")]
        public string MessageId { get; set; } = default!;
    }
}