//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    
    public class DeleteTopicSubscriberIdentifierDto
    {

        /// <summary>
        /// Unique identifier for this subscription. If provided, deletes only this specific subscription.
        /// </summary>
        [JsonProperty("identifier")]
        public string? Identifier { get; set; }

        /// <summary>
        /// The subscriber ID. If provided without identifier, deletes all subscriptions for this subscriber within the topic.
        /// </summary>
        [JsonProperty("subscriberId")]
        public string? SubscriberId { get; set; }
    }
}