//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;

    /// <summary>
    /// Reason for the dependency.
    /// </summary>
    public enum DependencyReasonEnum
    {
        [JsonProperty("LAYOUT_REQUIRED_FOR_WORKFLOW")]
        LayoutRequiredForWorkflow,
        [JsonProperty("LAYOUT_EXISTS_IN_TARGET")]
        LayoutExistsInTarget,
    }

    public static class DependencyReasonEnumExtension
    {
        public static string Value(this DependencyReasonEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DependencyReasonEnum ToEnum(this string value)
        {
            foreach(var field in typeof(DependencyReasonEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DependencyReasonEnum)
                    {
                        return (DependencyReasonEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DependencyReasonEnum");
        }
    }
}