//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;
    
    public enum DigestTimedConfigDtoWeekDays
    {
        [JsonProperty("monday")]
        Monday,
        [JsonProperty("tuesday")]
        Tuesday,
        [JsonProperty("wednesday")]
        Wednesday,
        [JsonProperty("thursday")]
        Thursday,
        [JsonProperty("friday")]
        Friday,
        [JsonProperty("saturday")]
        Saturday,
        [JsonProperty("sunday")]
        Sunday,
    }

    public static class DigestTimedConfigDtoWeekDaysExtension
    {
        public static string Value(this DigestTimedConfigDtoWeekDays value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DigestTimedConfigDtoWeekDays ToEnum(this string value)
        {
            foreach(var field in typeof(DigestTimedConfigDtoWeekDays).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DigestTimedConfigDtoWeekDays)
                    {
                        return (DigestTimedConfigDtoWeekDays)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DigestTimedConfigDtoWeekDays");
        }
    }

}