//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class DomainDiagnosticCheckDto
    {
        [JsonProperty("code")]
        public Code Code { get; set; } = default!;

        [JsonProperty("status")]
        public DomainDiagnosticCheckDtoStatus Status { get; set; } = default!;

        /// <summary>
        /// Round-trip time for this check in milliseconds.
        /// </summary>
        [JsonProperty("latencyMs")]
        public double LatencyMs { get; set; } = default!;
    }
}