//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class DomainRouteResponseDto
    {
        [JsonProperty("_id")]
        public string Id { get; set; } = default!;

        [JsonProperty("_domainId")]
        public string DomainId { get; set; } = default!;

        [JsonProperty("address")]
        public string Address { get; set; } = default!;

        /// <summary>
        /// Internal id of the destination agent. Only present for agent routes.
        /// </summary>
        [JsonProperty("agentId")]
        public string? AgentId { get; set; }

        [JsonProperty("type")]
        public DomainRouteResponseDtoType Type { get; set; } = default!;

        [JsonProperty("_environmentId")]
        public string EnvironmentId { get; set; } = default!;

        [JsonProperty("_organizationId")]
        public string OrganizationId { get; set; } = default!;

        [JsonProperty("createdAt")]
        public string CreatedAt { get; set; } = default!;

        [JsonProperty("updatedAt")]
        public string UpdatedAt { get; set; } = default!;

        /// <summary>
        /// String key-value metadata (max 10 keys, 500 characters total when set via API).
        /// </summary>
        [JsonProperty("data")]
        public Dictionary<string, string>? Data { get; set; }
    }
}