//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class EditPayloadDto
    {
        /// <summary>
        /// Platform message id of the message to edit.
        /// </summary>
        [JsonProperty("messageId")]
        public string MessageId { get; set; } = default!;

        /// <summary>
        /// Replacement content. Exactly one of markdown, card, or toolApprovalCard.
        /// </summary>
        [JsonProperty("content", NullValueHandling = NullValueHandling.Include)]
        public Content Content { get; set; } = default!;
    }
}