//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class EmailBlock
    {

        /// <summary>
        /// Type of the email block
        /// </summary>
        [JsonProperty("type")]
        public EmailBlockTypeEnum Type { get; set; } = default!;

        /// <summary>
        /// Content of the email block
        /// </summary>
        [JsonProperty("content")]
        public string Content { get; set; } = default!;

        /// <summary>
        /// URL associated with the email block, if any
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// Styles applied to the email block
        /// </summary>
        [JsonProperty("styles")]
        public EmailBlockStyles? Styles { get; set; }
    }
}