//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class EndpointType
    {
        private EndpointType(string value) { Value = value; }

        public string Value { get; private set; }

        public static EndpointType SlackChannelEndpointDto { get { return new EndpointType("SlackChannelEndpointDto"); } }

        public static EndpointType SlackUserEndpointDto { get { return new EndpointType("SlackUserEndpointDto"); } }

        public static EndpointType WebhookEndpointDto { get { return new EndpointType("WebhookEndpointDto"); } }

        public static EndpointType PhoneEndpointDto { get { return new EndpointType("PhoneEndpointDto"); } }

        public static EndpointType MsTeamsChannelEndpointDto { get { return new EndpointType("MsTeamsChannelEndpointDto"); } }

        public static EndpointType MsTeamsUserEndpointDto { get { return new EndpointType("MsTeamsUserEndpointDto"); } }

        public static EndpointType TelegramChatEndpointDto { get { return new EndpointType("TelegramChatEndpointDto"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(EndpointType v) { return v.Value; }
        public static EndpointType FromString(string v) {
            switch(v) {
                case "SlackChannelEndpointDto": return SlackChannelEndpointDto;
                case "SlackUserEndpointDto": return SlackUserEndpointDto;
                case "WebhookEndpointDto": return WebhookEndpointDto;
                case "PhoneEndpointDto": return PhoneEndpointDto;
                case "MsTeamsChannelEndpointDto": return MsTeamsChannelEndpointDto;
                case "MsTeamsUserEndpointDto": return MsTeamsUserEndpointDto;
                case "TelegramChatEndpointDto": return TelegramChatEndpointDto;
                default: throw new ArgumentException("Invalid value for EndpointType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((EndpointType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Endpoint data specific to the channel type.
    /// </summary>
    [JsonConverter(typeof(Endpoint.EndpointConverter))]
    public class Endpoint
    {
        public Endpoint(EndpointType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public SlackChannelEndpointDto? SlackChannelEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SlackUserEndpointDto? SlackUserEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public WebhookEndpointDto? WebhookEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public PhoneEndpointDto? PhoneEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public MsTeamsChannelEndpointDto? MsTeamsChannelEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public MsTeamsUserEndpointDto? MsTeamsUserEndpointDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public TelegramChatEndpointDto? TelegramChatEndpointDto { get; set; }

        public EndpointType Type { get; set; }
        public static Endpoint CreateSlackChannelEndpointDto(SlackChannelEndpointDto slackChannelEndpointDto)
        {
            EndpointType typ = EndpointType.SlackChannelEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.SlackChannelEndpointDto = slackChannelEndpointDto;
            return res;
        }
        public static Endpoint CreateSlackUserEndpointDto(SlackUserEndpointDto slackUserEndpointDto)
        {
            EndpointType typ = EndpointType.SlackUserEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.SlackUserEndpointDto = slackUserEndpointDto;
            return res;
        }
        public static Endpoint CreateWebhookEndpointDto(WebhookEndpointDto webhookEndpointDto)
        {
            EndpointType typ = EndpointType.WebhookEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.WebhookEndpointDto = webhookEndpointDto;
            return res;
        }
        public static Endpoint CreatePhoneEndpointDto(PhoneEndpointDto phoneEndpointDto)
        {
            EndpointType typ = EndpointType.PhoneEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.PhoneEndpointDto = phoneEndpointDto;
            return res;
        }
        public static Endpoint CreateMsTeamsChannelEndpointDto(MsTeamsChannelEndpointDto msTeamsChannelEndpointDto)
        {
            EndpointType typ = EndpointType.MsTeamsChannelEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.MsTeamsChannelEndpointDto = msTeamsChannelEndpointDto;
            return res;
        }
        public static Endpoint CreateMsTeamsUserEndpointDto(MsTeamsUserEndpointDto msTeamsUserEndpointDto)
        {
            EndpointType typ = EndpointType.MsTeamsUserEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.MsTeamsUserEndpointDto = msTeamsUserEndpointDto;
            return res;
        }
        public static Endpoint CreateTelegramChatEndpointDto(TelegramChatEndpointDto telegramChatEndpointDto)
        {
            EndpointType typ = EndpointType.TelegramChatEndpointDto;

            Endpoint res = new Endpoint(typ);
            res.TelegramChatEndpointDto = telegramChatEndpointDto;
            return res;
        }

        public class EndpointConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Endpoint);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Endpoint(EndpointType.SlackChannelEndpointDto)
                    {
                        SlackChannelEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SlackChannelEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SlackChannelEndpointDto), new Endpoint(EndpointType.SlackChannelEndpointDto), "SlackChannelEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.SlackUserEndpointDto)
                    {
                        SlackUserEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SlackUserEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SlackUserEndpointDto), new Endpoint(EndpointType.SlackUserEndpointDto), "SlackUserEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.PhoneEndpointDto)
                    {
                        PhoneEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<PhoneEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(PhoneEndpointDto), new Endpoint(EndpointType.PhoneEndpointDto), "PhoneEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.MsTeamsUserEndpointDto)
                    {
                        MsTeamsUserEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<MsTeamsUserEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(MsTeamsUserEndpointDto), new Endpoint(EndpointType.MsTeamsUserEndpointDto), "MsTeamsUserEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.TelegramChatEndpointDto)
                    {
                        TelegramChatEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TelegramChatEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TelegramChatEndpointDto), new Endpoint(EndpointType.TelegramChatEndpointDto), "TelegramChatEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.WebhookEndpointDto)
                    {
                        WebhookEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<WebhookEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(WebhookEndpointDto), new Endpoint(EndpointType.WebhookEndpointDto), "WebhookEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Endpoint(EndpointType.MsTeamsChannelEndpointDto)
                    {
                        MsTeamsChannelEndpointDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<MsTeamsChannelEndpointDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(MsTeamsChannelEndpointDto), new Endpoint(EndpointType.MsTeamsChannelEndpointDto), "MsTeamsChannelEndpointDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Endpoint res = (Endpoint)value;

                if (res.SlackChannelEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SlackChannelEndpointDto));
                    return;
                }

                if (res.SlackUserEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SlackUserEndpointDto));
                    return;
                }

                if (res.WebhookEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.WebhookEndpointDto));
                    return;
                }

                if (res.PhoneEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.PhoneEndpointDto));
                    return;
                }

                if (res.MsTeamsChannelEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MsTeamsChannelEndpointDto));
                    return;
                }

                if (res.MsTeamsUserEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MsTeamsUserEndpointDto));
                    return;
                }

                if (res.TelegramChatEndpointDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TelegramChatEndpointDto));
                    return;
                }
            }

        }

    }
}