//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;

    public class EnvironmentVariableValueResponseDto
    {
        [JsonProperty("_environmentId")]
        public string EnvironmentId { get; set; } = default!;

        /// <summary>
        /// Value is masked (••••••••) for secret variables.
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; } = default!;
    }
}