//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class FailedWorkflowDto
    {
        /// <summary>
        /// Type of the layout.
        /// </summary>
        [JsonProperty("resourceType")]
        public ResourceTypeEnum ResourceType { get; set; } = default!;

        /// <summary>
        /// Resource ID.
        /// </summary>
        [JsonProperty("resourceId")]
        public string ResourceId { get; set; } = default!;

        /// <summary>
        /// Resource name.
        /// </summary>
        [JsonProperty("resourceName")]
        public string ResourceName { get; set; } = default!;

        /// <summary>
        /// Error message.
        /// </summary>
        [JsonProperty("error")]
        public string Error { get; set; } = default!;

        /// <summary>
        /// Error stack trace.
        /// </summary>
        [JsonProperty("stack")]
        public string? Stack { get; set; }
    }
}