//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class FailedAssignmentsDto
    {

        /// <summary>
        /// List of subscriber IDs that were not found
        /// </summary>
        [JsonProperty("notFound")]
        public List<string>? NotFound { get; set; }
    }
}