//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;

    public class FileRefDto
    {
        /// <summary>
        /// Filename shown to the end user, including extension.
        /// </summary>
        [JsonProperty("filename")]
        public string Filename { get; set; } = default!;

        /// <summary>
        /// IANA MIME type of the file.
        /// </summary>
        [JsonProperty("mimeType")]
        public string? MimeType { get; set; }

        /// <summary>
        /// Base64-encoded inline file bytes. Mutually exclusive with `url`. Decoded size must be ≤ 5 MB. Prefer `url` for larger files.
        /// </summary>
        [JsonProperty("data")]
        public string? Data { get; set; }

        /// <summary>
        /// Publicly accessible HTTP(S) URL. Mutually exclusive with `data`. Server-side limits: 25 MB per file, 15 files per message, 50 MB aggregate.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }
    }
}