//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class FilterTopicsResponseDto
    {

        /// <summary>
        /// The list of topics
        /// </summary>
        [JsonProperty("data")]
        public List<TopicDto> Data { get; set; } = default!;

        /// <summary>
        /// The current page number
        /// </summary>
        [JsonProperty("page")]
        public double Page { get; set; } = default!;

        /// <summary>
        /// The number of items per page
        /// </summary>
        [JsonProperty("pageSize")]
        public double PageSize { get; set; } = default!;

        /// <summary>
        /// The total number of items
        /// </summary>
        [JsonProperty("totalCount")]
        public double TotalCount { get; set; } = default!;
    }
}