//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;

    public enum GeneratePreviewResponseDtoResult6Type
    {
        [JsonProperty("push")]
        Push,
    }

    public static class GeneratePreviewResponseDtoResult6TypeExtension
    {
        public static string Value(this GeneratePreviewResponseDtoResult6Type value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GeneratePreviewResponseDtoResult6Type ToEnum(this string value)
        {
            foreach(var field in typeof(GeneratePreviewResponseDtoResult6Type).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GeneratePreviewResponseDtoResult6Type)
                    {
                        return (GeneratePreviewResponseDtoResult6Type)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GeneratePreviewResponseDtoResult6Type");
        }
    }
}