//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class GenerateLinkUserOauthUrlRequestDtoContextType
    {
        private GenerateLinkUserOauthUrlRequestDtoContextType(string value) { Value = value; }

        public string Value { get; private set; }

        public static GenerateLinkUserOauthUrlRequestDtoContextType Str { get { return new GenerateLinkUserOauthUrlRequestDtoContextType("str"); } }

        public static GenerateLinkUserOauthUrlRequestDtoContextType GenerateLinkUserOauthUrlRequestDtoContext2 { get { return new GenerateLinkUserOauthUrlRequestDtoContextType("GenerateLinkUserOauthUrlRequestDto_context_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(GenerateLinkUserOauthUrlRequestDtoContextType v) { return v.Value; }
        public static GenerateLinkUserOauthUrlRequestDtoContextType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "GenerateLinkUserOauthUrlRequestDto_context_2": return GenerateLinkUserOauthUrlRequestDtoContext2;
                default: throw new ArgumentException("Invalid value for GenerateLinkUserOauthUrlRequestDtoContextType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((GenerateLinkUserOauthUrlRequestDtoContextType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(GenerateLinkUserOauthUrlRequestDtoContext.GenerateLinkUserOauthUrlRequestDtoContextConverter))]
    public class GenerateLinkUserOauthUrlRequestDtoContext
    {
        public GenerateLinkUserOauthUrlRequestDtoContext(GenerateLinkUserOauthUrlRequestDtoContextType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public GenerateLinkUserOauthUrlRequestDtoContext2? GenerateLinkUserOauthUrlRequestDtoContext2 { get; set; }

        public GenerateLinkUserOauthUrlRequestDtoContextType Type { get; set; }
        public static GenerateLinkUserOauthUrlRequestDtoContext CreateStr(string str)
        {
            GenerateLinkUserOauthUrlRequestDtoContextType typ = GenerateLinkUserOauthUrlRequestDtoContextType.Str;

            GenerateLinkUserOauthUrlRequestDtoContext res = new GenerateLinkUserOauthUrlRequestDtoContext(typ);
            res.Str = str;
            return res;
        }
        public static GenerateLinkUserOauthUrlRequestDtoContext CreateGenerateLinkUserOauthUrlRequestDtoContext2(GenerateLinkUserOauthUrlRequestDtoContext2 generateLinkUserOauthURLRequestDtoContext2)
        {
            GenerateLinkUserOauthUrlRequestDtoContextType typ = GenerateLinkUserOauthUrlRequestDtoContextType.GenerateLinkUserOauthUrlRequestDtoContext2;

            GenerateLinkUserOauthUrlRequestDtoContext res = new GenerateLinkUserOauthUrlRequestDtoContext(typ);
            res.GenerateLinkUserOauthUrlRequestDtoContext2 = generateLinkUserOauthURLRequestDtoContext2;
            return res;
        }

        public class GenerateLinkUserOauthUrlRequestDtoContextConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(GenerateLinkUserOauthUrlRequestDtoContext);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new GenerateLinkUserOauthUrlRequestDtoContext(GenerateLinkUserOauthUrlRequestDtoContextType.GenerateLinkUserOauthUrlRequestDtoContext2)
                    {
                        GenerateLinkUserOauthUrlRequestDtoContext2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<GenerateLinkUserOauthUrlRequestDtoContext2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(GenerateLinkUserOauthUrlRequestDtoContext2), new GenerateLinkUserOauthUrlRequestDtoContext(GenerateLinkUserOauthUrlRequestDtoContextType.GenerateLinkUserOauthUrlRequestDtoContext2), "GenerateLinkUserOauthUrlRequestDtoContext2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new GenerateLinkUserOauthUrlRequestDtoContext(GenerateLinkUserOauthUrlRequestDtoContextType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                GenerateLinkUserOauthUrlRequestDtoContext res = (GenerateLinkUserOauthUrlRequestDtoContext)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.GenerateLinkUserOauthUrlRequestDtoContext2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GenerateLinkUserOauthUrlRequestDtoContext2));
                    return;
                }
            }

        }

    }
}