//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class HumanSignalDto
    {
        [JsonProperty("type")]
        public HumanSignalDtoType Type { get; set; } = default!;

        /// <summary>
        /// Interaction verb queued by `ctx.ask` / `ctx.approve` / `ctx.choose` / `ctx.tell`.
        /// </summary>
        [JsonProperty("kind")]
        public Kind Kind { get; set; } = default!;

        /// <summary>
        /// Question, action description, or one-way message shown to the human.
        /// </summary>
        [JsonProperty("prompt")]
        public string Prompt { get; set; } = default!;

        /// <summary>
        /// Client-minted id returned by the framework helper; echoed on `ctx.humanResponse.requestId`.
        /// </summary>
        [JsonProperty("requestId")]
        public string RequestId { get; set; } = default!;

        /// <summary>
        /// Choice labels — required for `choose`, ignored otherwise.
        /// </summary>
        [JsonProperty("options")]
        public List<string>? Options { get; set; }

        /// <summary>
        /// Attribution label rendered in the card.
        /// </summary>
        [JsonProperty("from")]
        public string? From { get; set; }

        /// <summary>
        /// Seconds until the interaction expires. Default 86400 (24h), max 259200.
        /// </summary>
        [JsonProperty("ttlSeconds")]
        public double? TtlSeconds { get; set; }

        /// <summary>
        /// Novu subscriberId(s) allowed to settle this interaction (max 50). First valid answer wins. When omitted, the conversation subscriber is used. Subscriber ids only — not workflow topic recipients.
        /// </summary>
        [JsonProperty("to", NullValueHandling = NullValueHandling.Include)]
        public HumanSignalDtoTo? To { get; set; }
    }
}