//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class ImportMasterJsonRequestDto
    {

        /// <summary>
        /// The locale for which translations are being imported
        /// </summary>
        [JsonProperty("locale")]
        public string Locale { get; set; } = default!;

        /// <summary>
        /// Master JSON object containing all translations organized by workflow identifier
        /// </summary>
        [JsonProperty("masterJson")]
        public Dictionary<string, object> MasterJson { get; set; } = default!;
    }
}