//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class InboxActionDto
    {
        /// <summary>
        /// Label of the action button.
        /// </summary>
        [JsonProperty("label")]
        public string Label { get; set; } = default!;

        /// <summary>
        /// Whether the action has been completed.
        /// </summary>
        [JsonProperty("isCompleted")]
        public bool IsCompleted { get; set; } = default!;

        /// <summary>
        /// Redirect configuration for the action.
        /// </summary>
        [JsonProperty("redirect")]
        public RedirectDto? Redirect { get; set; }
    }
}