//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;
    
    public enum LayoutResponseDtoSortField
    {
        [JsonProperty("createdAt")]
        CreatedAt,
        [JsonProperty("updatedAt")]
        UpdatedAt,
        [JsonProperty("name")]
        Name,
    }

    public static class LayoutResponseDtoSortFieldExtension
    {
        public static string Value(this LayoutResponseDtoSortField value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LayoutResponseDtoSortField ToEnum(this string value)
        {
            foreach(var field in typeof(LayoutResponseDtoSortField).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LayoutResponseDtoSortField)
                    {
                        return (LayoutResponseDtoSortField)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LayoutResponseDtoSortField");
        }
    }

}