//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class ListTopicSubscriptionsResponseDto
    {

        /// <summary>
        /// List of returned Topic Subscriptions
        /// </summary>
        [JsonProperty("data")]
        public List<TopicSubscriptionResponseDto> Data { get; set; } = default!;

        /// <summary>
        /// The cursor for the next page of results, or null if there are no more pages.
        /// </summary>
        [JsonProperty("next", NullValueHandling = NullValueHandling.Include)]
        public string? Next { get; set; }

        /// <summary>
        /// The cursor for the previous page of results, or null if this is the first page.
        /// </summary>
        [JsonProperty("previous", NullValueHandling = NullValueHandling.Include)]
        public string? Previous { get; set; }

        /// <summary>
        /// The total count of items (up to 50,000)
        /// </summary>
        [JsonProperty("totalCount")]
        public double TotalCount { get; set; } = default!;

        /// <summary>
        /// Whether there are more than 50,000 results available
        /// </summary>
        [JsonProperty("totalCountCapped")]
        public bool TotalCountCapped { get; set; } = default!;
    }
}