//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class LookBackWindowDto
    {

        /// <summary>
        /// Amount of time for the look-back window.
        /// </summary>
        [JsonProperty("amount")]
        public double Amount { get; set; } = default!;

        /// <summary>
        /// Unit of time for the look-back window.
        /// </summary>
        [JsonProperty("unit")]
        public LookBackWindowDtoUnit Unit { get; set; } = default!;
    }
}