//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class ManagedRuntimeDto
    {
        [JsonProperty("providerId")]
        public ProviderId ProviderId { get; set; } = default!;

        /// <summary>
        /// ID of an existing Novu integration (kind: "agent") that holds the provider API key and provisioned environment. Create the integration first via POST /integrations.
        /// </summary>
        [JsonProperty("integrationId")]
        public string IntegrationId { get; set; } = default!;

        /// <summary>
        /// ID of an existing agent on the provider platform. When set, Novu adopts the agent instead of creating a new one.
        /// </summary>
        [JsonProperty("externalAgentId")]
        public string? ExternalAgentId { get; set; }

        /// <summary>
        /// ID of an existing environment on the provider platform. When set, Novu adopts the environment.
        /// </summary>
        [JsonProperty("externalEnvironmentId")]
        public string? ExternalEnvironmentId { get; set; }

        [JsonProperty("model")]
        public string? Model { get; set; }

        [JsonProperty("systemPrompt")]
        public string? SystemPrompt { get; set; }

        [JsonProperty("tools")]
        public List<string>? Tools { get; set; }

        [JsonProperty("mcpServers")]
        public List<string>? McpServers { get; set; }

        [JsonProperty("skills")]
        public List<AgentSkillInputDto>? Skills { get; set; }
    }
}