//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class MarkAllMessageAsRequestDto
    {

        /// <summary>
        /// Optional feed identifier or array of feed identifiers
        /// </summary>
        [JsonProperty("feedIdentifier")]
        public FeedIdentifier? FeedIdentifier { get; set; }

        /// <summary>
        /// Mark all subscriber messages as read, unread, seen or unseen
        /// </summary>
        [JsonProperty("markAs")]
        public MarkAs MarkAs { get; set; } = default!;
    }
}