//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class MessageResponseDtoContentType
    {
        private MessageResponseDtoContentType(string value) { Value = value; }

        public string Value { get; private set; }

        public static MessageResponseDtoContentType ArrayOfEmailBlock { get { return new MessageResponseDtoContentType("arrayOfEmailBlock"); } }

        public static MessageResponseDtoContentType Str { get { return new MessageResponseDtoContentType("str"); } }

        public static MessageResponseDtoContentType Null { get { return new MessageResponseDtoContentType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MessageResponseDtoContentType v) { return v.Value; }
        public static MessageResponseDtoContentType FromString(string v) {
            switch(v) {
                case "arrayOfEmailBlock": return ArrayOfEmailBlock;
                case "str": return Str;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for MessageResponseDtoContentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MessageResponseDtoContentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Content of the message, can be an email block or a string
    /// </summary>
    [JsonConverter(typeof(MessageResponseDtoContent.MessageResponseDtoContentConverter))]
    public class MessageResponseDtoContent
    {
        public MessageResponseDtoContent(MessageResponseDtoContentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<EmailBlock>? ArrayOfEmailBlock { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        public MessageResponseDtoContentType Type { get; set; }
        public static MessageResponseDtoContent CreateArrayOfEmailBlock(List<EmailBlock> arrayOfEmailBlock)
        {
            MessageResponseDtoContentType typ = MessageResponseDtoContentType.ArrayOfEmailBlock;

            MessageResponseDtoContent res = new MessageResponseDtoContent(typ);
            res.ArrayOfEmailBlock = arrayOfEmailBlock;
            return res;
        }
        public static MessageResponseDtoContent CreateStr(string str)
        {
            MessageResponseDtoContentType typ = MessageResponseDtoContentType.Str;

            MessageResponseDtoContent res = new MessageResponseDtoContent(typ);
            res.Str = str;
            return res;
        }

        public static MessageResponseDtoContent CreateNull()
        {
            MessageResponseDtoContentType typ = MessageResponseDtoContentType.Null;
            return new MessageResponseDtoContent(typ);
        }

        public class MessageResponseDtoContentConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(MessageResponseDtoContent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new MessageResponseDtoContent(MessageResponseDtoContentType.ArrayOfEmailBlock)
                    {
                        ArrayOfEmailBlock = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<EmailBlock>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<EmailBlock>), new MessageResponseDtoContent(MessageResponseDtoContentType.ArrayOfEmailBlock), "ArrayOfEmailBlock"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new MessageResponseDtoContent(MessageResponseDtoContentType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                MessageResponseDtoContent res = (MessageResponseDtoContent)value;
                if (MessageResponseDtoContentType.FromString(res.Type).Equals(MessageResponseDtoContentType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.ArrayOfEmailBlock != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfEmailBlock));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
            }

        }

    }
}