//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    
    public class MetaDto
    {

        /// <summary>
        /// The total count of subscriber IDs provided
        /// </summary>
        [JsonProperty("totalCount")]
        public double TotalCount { get; set; } = default!;

        /// <summary>
        /// The count of successfully created subscriptions
        /// </summary>
        [JsonProperty("successful")]
        public double Successful { get; set; } = default!;

        /// <summary>
        /// The count of failed subscription attempts
        /// </summary>
        [JsonProperty("failed")]
        public double Failed { get; set; } = default!;
    }
}