//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;
    
    /// <summary>
    /// Type of monthly schedule
    /// </summary>
    public enum MonthlyTypeEnum
    {
        [JsonProperty("each")]
        Each,
        [JsonProperty("on")]
        On,
    }

    public static class MonthlyTypeEnumExtension
    {
        public static string Value(this MonthlyTypeEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static MonthlyTypeEnum ToEnum(this string value)
        {
            foreach(var field in typeof(MonthlyTypeEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is MonthlyTypeEnum)
                    {
                        return (MonthlyTypeEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum MonthlyTypeEnum");
        }
    }

}