//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class NotificationStepDataMetadataType
    {
        private NotificationStepDataMetadataType(string value) { Value = value; }

        public string Value { get; private set; }

        public static NotificationStepDataMetadataType DigestRegularMetadata { get { return new NotificationStepDataMetadataType("DigestRegularMetadata"); } }

        public static NotificationStepDataMetadataType DigestTimedMetadata { get { return new NotificationStepDataMetadataType("DigestTimedMetadata"); } }

        public static NotificationStepDataMetadataType DelayRegularMetadata { get { return new NotificationStepDataMetadataType("DelayRegularMetadata"); } }

        public static NotificationStepDataMetadataType DelayScheduledMetadata { get { return new NotificationStepDataMetadataType("DelayScheduledMetadata"); } }

        public static NotificationStepDataMetadataType Null { get { return new NotificationStepDataMetadataType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(NotificationStepDataMetadataType v) { return v.Value; }
        public static NotificationStepDataMetadataType FromString(string v) {
            switch(v) {
                case "DigestRegularMetadata": return DigestRegularMetadata;
                case "DigestTimedMetadata": return DigestTimedMetadata;
                case "DelayRegularMetadata": return DelayRegularMetadata;
                case "DelayScheduledMetadata": return DelayScheduledMetadata;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for NotificationStepDataMetadataType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((NotificationStepDataMetadataType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Metadata associated with the workflow step. Can vary based on the type of step.
    /// </summary>
    [JsonConverter(typeof(NotificationStepDataMetadata.NotificationStepDataMetadataConverter))]
    public class NotificationStepDataMetadata
    {
        public NotificationStepDataMetadata(NotificationStepDataMetadataType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public DigestRegularMetadata? DigestRegularMetadata { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public DigestTimedMetadata? DigestTimedMetadata { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public DelayRegularMetadata? DelayRegularMetadata { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public DelayScheduledMetadata? DelayScheduledMetadata { get; set; }

        public NotificationStepDataMetadataType Type { get; set; }
        public static NotificationStepDataMetadata CreateDigestRegularMetadata(DigestRegularMetadata digestRegularMetadata)
        {
            NotificationStepDataMetadataType typ = NotificationStepDataMetadataType.DigestRegularMetadata;

            NotificationStepDataMetadata res = new NotificationStepDataMetadata(typ);
            res.DigestRegularMetadata = digestRegularMetadata;
            return res;
        }
        public static NotificationStepDataMetadata CreateDigestTimedMetadata(DigestTimedMetadata digestTimedMetadata)
        {
            NotificationStepDataMetadataType typ = NotificationStepDataMetadataType.DigestTimedMetadata;

            NotificationStepDataMetadata res = new NotificationStepDataMetadata(typ);
            res.DigestTimedMetadata = digestTimedMetadata;
            return res;
        }
        public static NotificationStepDataMetadata CreateDelayRegularMetadata(DelayRegularMetadata delayRegularMetadata)
        {
            NotificationStepDataMetadataType typ = NotificationStepDataMetadataType.DelayRegularMetadata;

            NotificationStepDataMetadata res = new NotificationStepDataMetadata(typ);
            res.DelayRegularMetadata = delayRegularMetadata;
            return res;
        }
        public static NotificationStepDataMetadata CreateDelayScheduledMetadata(DelayScheduledMetadata delayScheduledMetadata)
        {
            NotificationStepDataMetadataType typ = NotificationStepDataMetadataType.DelayScheduledMetadata;

            NotificationStepDataMetadata res = new NotificationStepDataMetadata(typ);
            res.DelayScheduledMetadata = delayScheduledMetadata;
            return res;
        }

        public static NotificationStepDataMetadata CreateNull()
        {
            NotificationStepDataMetadataType typ = NotificationStepDataMetadataType.Null;
            return new NotificationStepDataMetadata(typ);
        }

        public class NotificationStepDataMetadataConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(NotificationStepDataMetadata);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new NotificationStepDataMetadata(NotificationStepDataMetadataType.DelayScheduledMetadata)
                    {
                        DelayScheduledMetadata = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DelayScheduledMetadata>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DelayScheduledMetadata), new NotificationStepDataMetadata(NotificationStepDataMetadataType.DelayScheduledMetadata), "DelayScheduledMetadata"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new NotificationStepDataMetadata(NotificationStepDataMetadataType.DelayRegularMetadata)
                    {
                        DelayRegularMetadata = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DelayRegularMetadata>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DelayRegularMetadata), new NotificationStepDataMetadata(NotificationStepDataMetadataType.DelayRegularMetadata), "DelayRegularMetadata"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new NotificationStepDataMetadata(NotificationStepDataMetadataType.DigestTimedMetadata)
                    {
                        DigestTimedMetadata = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DigestTimedMetadata>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DigestTimedMetadata), new NotificationStepDataMetadata(NotificationStepDataMetadataType.DigestTimedMetadata), "DigestTimedMetadata"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new NotificationStepDataMetadata(NotificationStepDataMetadataType.DigestRegularMetadata)
                    {
                        DigestRegularMetadata = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DigestRegularMetadata>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DigestRegularMetadata), new NotificationStepDataMetadata(NotificationStepDataMetadataType.DigestRegularMetadata), "DigestRegularMetadata"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                NotificationStepDataMetadata res = (NotificationStepDataMetadata)value;
                if (NotificationStepDataMetadataType.FromString(res.Type).Equals(NotificationStepDataMetadataType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.DigestRegularMetadata != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DigestRegularMetadata));
                    return;
                }

                if (res.DigestTimedMetadata != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DigestTimedMetadata));
                    return;
                }

                if (res.DelayRegularMetadata != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DelayRegularMetadata));
                    return;
                }

                if (res.DelayScheduledMetadata != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DelayScheduledMetadata));
                    return;
                }
            }

        }

    }
}