//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class NotificationTrigger
    {
        [JsonProperty("type")]
        public NotificationTriggerType Type { get; set; } = default!;

        [JsonProperty("identifier")]
        public string Identifier { get; set; } = default!;

        [JsonProperty("variables")]
        public List<NotificationTriggerVariable> Variables { get; set; } = default!;

        [JsonProperty("subscriberVariables")]
        public List<NotificationTriggerVariable>? SubscriberVariables { get; set; }
    }
}