//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class OpsgenieIntegrationEndpointDto
    {
        /// <summary>
        /// Opsgenie API integration key (GenieKey) in UUID format. Encrypted at rest on the channel endpoint (`endpoint` field).
        /// </summary>
        [JsonProperty("apiKey")]
        public string ApiKey { get; set; } = default!;

        /// <summary>
        /// Opsgenie account region that determines the alert API data-center endpoint.
        /// </summary>
        [JsonProperty("region")]
        public OpsgenieIntegrationEndpointDtoRegion Region { get; set; } = default!;
    }
}