//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class PlaceholderType
    {
        private PlaceholderType(string value) { Value = value; }

        public string Value { get; private set; }

        public static PlaceholderType Str { get { return new PlaceholderType("str"); } }

        public static PlaceholderType Number { get { return new PlaceholderType("number"); } }

        public static PlaceholderType Boolean { get { return new PlaceholderType("boolean"); } }

        public static PlaceholderType MapOfAny { get { return new PlaceholderType("mapOfAny"); } }

        public static PlaceholderType ArrayOfPlaceholder5 { get { return new PlaceholderType("arrayOfPlaceholder5"); } }

        public static PlaceholderType Null { get { return new PlaceholderType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(PlaceholderType v) { return v.Value; }
        public static PlaceholderType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "number": return Number;
                case "boolean": return Boolean;
                case "mapOfAny": return MapOfAny;
                case "arrayOfPlaceholder5": return ArrayOfPlaceholder5;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for PlaceholderType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((PlaceholderType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Placeholder for the UI Schema Property
    /// </summary>
    [JsonConverter(typeof(Placeholder.PlaceholderConverter))]
    public class Placeholder
    {
        public Placeholder(PlaceholderType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<Placeholder5>? ArrayOfPlaceholder5 { get; set; }

        public PlaceholderType Type { get; set; }
        public static Placeholder CreateStr(string str)
        {
            PlaceholderType typ = PlaceholderType.Str;

            Placeholder res = new Placeholder(typ);
            res.Str = str;
            return res;
        }
        public static Placeholder CreateNumber(double number)
        {
            PlaceholderType typ = PlaceholderType.Number;

            Placeholder res = new Placeholder(typ);
            res.Number = number;
            return res;
        }
        public static Placeholder CreateBoolean(bool boolean)
        {
            PlaceholderType typ = PlaceholderType.Boolean;

            Placeholder res = new Placeholder(typ);
            res.Boolean = boolean;
            return res;
        }
        public static Placeholder CreateMapOfAny(Dictionary<string, object> mapOfAny)
        {
            PlaceholderType typ = PlaceholderType.MapOfAny;

            Placeholder res = new Placeholder(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }
        public static Placeholder CreateArrayOfPlaceholder5(List<Placeholder5> arrayOfPlaceholder5)
        {
            PlaceholderType typ = PlaceholderType.ArrayOfPlaceholder5;

            Placeholder res = new Placeholder(typ);
            res.ArrayOfPlaceholder5 = arrayOfPlaceholder5;
            return res;
        }

        public static Placeholder CreateNull()
        {
            PlaceholderType typ = PlaceholderType.Null;
            return new Placeholder(typ);
        }

        public class PlaceholderConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(Placeholder);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new Placeholder(PlaceholderType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new Placeholder(PlaceholderType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new Placeholder(PlaceholderType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new Placeholder(PlaceholderType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new Placeholder(PlaceholderType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Placeholder(PlaceholderType.ArrayOfPlaceholder5)
                    {
                        ArrayOfPlaceholder5 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<Placeholder5>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<Placeholder5>), new Placeholder(PlaceholderType.ArrayOfPlaceholder5), "ArrayOfPlaceholder5"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }

                Placeholder res = (Placeholder)value;
                if (PlaceholderType.FromString(res.Type).Equals(PlaceholderType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

                if (res.ArrayOfPlaceholder5 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfPlaceholder5));
                    return;
                }
            }

        }

    }
}