//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class PublishEnvironmentResponseDto
    {
        /// <summary>
        /// Sync results by resource type.
        /// </summary>
        [JsonProperty("results")]
        public List<SyncResultDto> Results { get; set; } = default!;

        /// <summary>
        /// Summary of the sync operation.
        /// </summary>
        [JsonProperty("summary")]
        public PublishSummaryDto Summary { get; set; } = default!;
    }
}