//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class ResourceDependencyDto
    {
        /// <summary>
        /// Type of the layout.
        /// </summary>
        [JsonProperty("resourceType")]
        public ResourceTypeEnum ResourceType { get; set; } = default!;

        /// <summary>
        /// ID of the dependent resource.
        /// </summary>
        [JsonProperty("resourceId")]
        public string ResourceId { get; set; } = default!;

        /// <summary>
        /// Name of the dependent resource.
        /// </summary>
        [JsonProperty("resourceName")]
        public string ResourceName { get; set; } = default!;

        /// <summary>
        /// Whether this dependency blocks the operation.
        /// </summary>
        [JsonProperty("isBlocking")]
        public bool IsBlocking { get; set; } = default!;

        /// <summary>
        /// Reason for the dependency.
        /// </summary>
        [JsonProperty("reason")]
        public DependencyReasonEnum Reason { get; set; } = default!;
    }
}