//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class ResourceDiffDto
    {
        /// <summary>
        /// Source resource information.
        /// </summary>
        [JsonProperty("sourceResource")]
        public ResourceDiffDtoSourceResource? SourceResource { get; set; } = null;

        /// <summary>
        /// Target resource information.
        /// </summary>
        [JsonProperty("targetResource")]
        public ResourceDiffDtoTargetResource? TargetResource { get; set; } = null;

        /// <summary>
        /// Type of the layout.
        /// </summary>
        [JsonProperty("resourceType")]
        public ResourceTypeEnum ResourceType { get; set; } = default!;

        /// <summary>
        /// Type of change.
        /// </summary>
        [JsonProperty("action")]
        public DiffActionEnum Action { get; set; } = default!;

        /// <summary>
        /// Detailed changes (only for modified resources).
        /// </summary>
        [JsonProperty("diffs")]
        public Diffs? Diffs { get; set; }

        /// <summary>
        /// Step type (only for step resources).
        /// </summary>
        [JsonProperty("stepType")]
        public string? StepType { get; set; }

        /// <summary>
        /// Previous index in steps array (for moved/deleted steps).
        /// </summary>
        [JsonProperty("previousIndex")]
        public double? PreviousIndex { get; set; }

        /// <summary>
        /// New index in steps array (for moved/added steps).
        /// </summary>
        [JsonProperty("newIndex")]
        public double? NewIndex { get; set; }
    }
}