//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class SmsStepUpsertDto
    {

        /// <summary>
        /// Database identifier of the step. Used for updating the step.
        /// </summary>
        [JsonProperty("_id")]
        public string? Id { get; set; }

        /// <summary>
        /// Unique identifier for the step
        /// </summary>
        [JsonProperty("stepId")]
        public string? StepId { get; set; }

        /// <summary>
        /// Name of the step
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Type of the step
        /// </summary>
        [JsonProperty("type")]
        public StepTypeEnum Type { get; set; } = default!;

        /// <summary>
        /// Control values for the SMS step.
        /// </summary>
        [JsonProperty("controlValues", NullValueHandling = NullValueHandling.Include)]
        public SmsStepUpsertDtoControlValues? ControlValues { get; set; }
    }
}