//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class StepIntegrationIssue
    {

        /// <summary>
        /// Type of integration issue
        /// </summary>
        [JsonProperty("issueType")]
        public StepIntegrationIssueEnum IssueType { get; set; } = default!;

        /// <summary>
        /// Name of the variable related to the issue
        /// </summary>
        [JsonProperty("variableName")]
        public string? VariableName { get; set; }

        /// <summary>
        /// Detailed message describing the issue
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }
}