//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class StepFilterDto
    {

        [JsonProperty("isNegated")]
        public bool IsNegated { get; set; } = default!;

        [JsonProperty("type")]
        public BuilderFieldTypeEnum Type { get; set; } = default!;

        [JsonProperty("value")]
        public StepFilterDtoValue Value { get; set; } = default!;

        [JsonProperty("children")]
        public List<FieldFilterPartDto> Children { get; set; } = default!;
    }
}