//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;

    public class StepsOverrides
    {
        /// <summary>
        /// Passing the provider id and the provider specific configurations.
        /// </summary>
        [JsonProperty("providers")]
        public Dictionary<string, Dictionary<string, object>>? Providers { get; set; }

        /// <summary>
        /// Override the or remove the layout for this specific step.
        /// </summary>
        [JsonProperty("layoutId")]
        public string? LayoutId { get; set; } = null;
    }
}