//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class StepIssuesDto
    {
        /// <summary>
        /// Controls-related issues.
        /// </summary>
        [JsonProperty("controls")]
        public Dictionary<string, List<StepContentIssueDto>>? Controls { get; set; }

        /// <summary>
        /// Integration-related issues.
        /// </summary>
        [JsonProperty("integration")]
        public Dictionary<string, List<StepIntegrationIssue>>? Integration { get; set; }
    }
}