//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;

    public class SubscriptionErrorDto
    {
        /// <summary>
        /// The subscriber ID that failed.
        /// </summary>
        [JsonProperty("subscriberId")]
        public string SubscriberId { get; set; } = default!;

        /// <summary>
        /// The error code.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        /// <summary>
        /// The error message.
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; } = default!;
    }
}