//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class SubscriptionDto
    {

        /// <summary>
        /// The unique identifier of the subscription
        /// </summary>
        [JsonProperty("_id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The topic information
        /// </summary>
        [JsonProperty("topic")]
        public TopicDto Topic { get; set; } = default!;

        /// <summary>
        /// The subscriber information
        /// </summary>
        [JsonProperty("subscriber", NullValueHandling = NullValueHandling.Include)]
        public Subscriber? Subscriber { get; set; }

        /// <summary>
        /// The creation date of the subscription
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt { get; set; } = default!;

        /// <summary>
        /// The last update date of the subscription
        /// </summary>
        [JsonProperty("updatedAt")]
        public string UpdatedAt { get; set; } = default!;
    }
}