//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    public class SubscriberGlobalPreferenceDto
    {

        /// <summary>
        /// Whether notifications are enabled globally
        /// </summary>
        [JsonProperty("enabled")]
        public bool Enabled { get; set; } = default!;

        /// <summary>
        /// Channel-specific preference settings
        /// </summary>
        [JsonProperty("channels")]
        public SubscriberPreferenceChannels Channels { get; set; } = default!;
    }
}