//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    

    public class SubscriberPayloadDtoDataType
    {
        private SubscriberPayloadDtoDataType(string value) { Value = value; }

        public string Value { get; private set; }
        public static SubscriberPayloadDtoDataType Str { get { return new SubscriberPayloadDtoDataType("str"); } }
        
        public static SubscriberPayloadDtoDataType ArrayOfStr { get { return new SubscriberPayloadDtoDataType("arrayOfStr"); } }
        
        public static SubscriberPayloadDtoDataType Boolean { get { return new SubscriberPayloadDtoDataType("boolean"); } }
        
        public static SubscriberPayloadDtoDataType Number { get { return new SubscriberPayloadDtoDataType("number"); } }
        
        public static SubscriberPayloadDtoDataType Null { get { return new SubscriberPayloadDtoDataType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SubscriberPayloadDtoDataType v) { return v.Value; }
        public static SubscriberPayloadDtoDataType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "arrayOfStr": return ArrayOfStr;
                case "boolean": return Boolean;
                case "number": return Number;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for SubscriberPayloadDtoDataType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SubscriberPayloadDtoDataType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(SubscriberPayloadDtoData.SubscriberPayloadDtoDataConverter))]
    public class SubscriberPayloadDtoData {
        public SubscriberPayloadDtoData(SubscriberPayloadDtoDataType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<string>? ArrayOfStr { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public double? Number { get; set; }

        public SubscriberPayloadDtoDataType Type { get; set; }


        public static SubscriberPayloadDtoData CreateStr(string str) {
            SubscriberPayloadDtoDataType typ = SubscriberPayloadDtoDataType.Str;

            SubscriberPayloadDtoData res = new SubscriberPayloadDtoData(typ);
            res.Str = str;
            return res;
        }

        public static SubscriberPayloadDtoData CreateArrayOfStr(List<string> arrayOfStr) {
            SubscriberPayloadDtoDataType typ = SubscriberPayloadDtoDataType.ArrayOfStr;

            SubscriberPayloadDtoData res = new SubscriberPayloadDtoData(typ);
            res.ArrayOfStr = arrayOfStr;
            return res;
        }

        public static SubscriberPayloadDtoData CreateBoolean(bool boolean) {
            SubscriberPayloadDtoDataType typ = SubscriberPayloadDtoDataType.Boolean;

            SubscriberPayloadDtoData res = new SubscriberPayloadDtoData(typ);
            res.Boolean = boolean;
            return res;
        }

        public static SubscriberPayloadDtoData CreateNumber(double number) {
            SubscriberPayloadDtoDataType typ = SubscriberPayloadDtoDataType.Number;

            SubscriberPayloadDtoData res = new SubscriberPayloadDtoData(typ);
            res.Number = number;
            return res;
        }

        public static SubscriberPayloadDtoData CreateNull() {
            SubscriberPayloadDtoDataType typ = SubscriberPayloadDtoDataType.Null;
            return new SubscriberPayloadDtoData(typ);
        }

        public class SubscriberPayloadDtoDataConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(SubscriberPayloadDtoData);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new SubscriberPayloadDtoData(SubscriberPayloadDtoDataType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    return new SubscriberPayloadDtoData(SubscriberPayloadDtoDataType.ArrayOfStr)
                    {
                        ArrayOfStr = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<string>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<string>), new SubscriberPayloadDtoData(SubscriberPayloadDtoDataType.ArrayOfStr), "ArrayOfStr"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new SubscriberPayloadDtoData(SubscriberPayloadDtoDataType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    var converted = Convert.ToDouble(json);
                    return new SubscriberPayloadDtoData(SubscriberPayloadDtoDataType.Number)
                    {
                        Number = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                SubscriberPayloadDtoData res = (SubscriberPayloadDtoData)value;
                if (SubscriberPayloadDtoDataType.FromString(res.Type).Equals(SubscriberPayloadDtoDataType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }
                if (res.ArrayOfStr != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfStr));
                    return;
                }
                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }
                if (res.Number != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Number));
                    return;
                }

            }

        }

    }
}