//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;

    /// <summary>
    /// Target resource information.
    /// </summary>
    public class TargetResource
    {
        /// <summary>
        /// Resource ID (workflow ID or step ID).
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Resource name (workflow name or step name).
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// User who last updated the resource.
        /// </summary>
        [JsonProperty("updatedBy")]
        public ResourceDiffResultDtoUpdatedBy? UpdatedBy { get; set; } = null;

        /// <summary>
        /// When the resource was last updated.
        /// </summary>
        [JsonProperty("updatedAt")]
        public DateTime? UpdatedAt { get; set; } = null;
    }
}