//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;

    public class TestDomainRouteAgentResultDto
    {
        [JsonProperty("agentId")]
        public string AgentId { get; set; } = default!;

        [JsonProperty("httpStatus")]
        public double HttpStatus { get; set; } = default!;

        /// <summary>
        /// Parsed JSON body from the agent webhook response when JSON.
        /// </summary>
        [JsonProperty("agentReply")]
        public AgentReply? AgentReply { get; set; }

        [JsonProperty("latencyMs")]
        public double LatencyMs { get; set; } = default!;
    }
}