//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;

    public class ToolApprovalRequestPayloadDto
    {
        /// <summary>
        /// Unique id for this approval request (matches the AI SDK approvalId).
        /// </summary>
        [JsonProperty("approvalId")]
        public string ApprovalId { get; set; } = default!;

        /// <summary>
        /// Id of the tool call awaiting approval.
        /// </summary>
        [JsonProperty("toolCallId")]
        public string ToolCallId { get; set; } = default!;

        /// <summary>
        /// Name of the gated tool.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Tool input the model proposed.
        /// </summary>
        [JsonProperty("input")]
        public Dictionary<string, object>? Input { get; set; }
    }
}