//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;

    /// <summary>
    /// Resource type.
    /// </summary>
    public enum TranslationResponseDtoResourceType
    {
        [JsonProperty("workflow")]
        Workflow,
        [JsonProperty("layout")]
        Layout,
    }

    public static class TranslationResponseDtoResourceTypeExtension
    {
        public static string Value(this TranslationResponseDtoResourceType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TranslationResponseDtoResourceType ToEnum(this string value)
        {
            foreach(var field in typeof(TranslationResponseDtoResourceType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TranslationResponseDtoResourceType)
                    {
                        return (TranslationResponseDtoResourceType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TranslationResponseDtoResourceType");
        }
    }
}