//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TriggerEventRequestDtoToType
    {
        private TriggerEventRequestDtoToType(string value) { Value = value; }

        public string Value { get; private set; }

        public static TriggerEventRequestDtoToType ArrayOfTo1 { get { return new TriggerEventRequestDtoToType("arrayOfTo1"); } }

        public static TriggerEventRequestDtoToType Str { get { return new TriggerEventRequestDtoToType("str"); } }

        public static TriggerEventRequestDtoToType SubscriberPayloadDto { get { return new TriggerEventRequestDtoToType("SubscriberPayloadDto"); } }

        public static TriggerEventRequestDtoToType TopicPayloadDto { get { return new TriggerEventRequestDtoToType("TopicPayloadDto"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TriggerEventRequestDtoToType v) { return v.Value; }
        public static TriggerEventRequestDtoToType FromString(string v) {
            switch(v) {
                case "arrayOfTo1": return ArrayOfTo1;
                case "str": return Str;
                case "SubscriberPayloadDto": return SubscriberPayloadDto;
                case "TopicPayloadDto": return TopicPayloadDto;
                default: throw new ArgumentException("Invalid value for TriggerEventRequestDtoToType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TriggerEventRequestDtoToType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The recipients list of people who will receive the notification. Maximum number of recipients can be 100.
    /// </summary>
    [JsonConverter(typeof(TriggerEventRequestDtoTo.TriggerEventRequestDtoToConverter))]
    public class TriggerEventRequestDtoTo
    {
        public TriggerEventRequestDtoTo(TriggerEventRequestDtoToType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public List<To1>? ArrayOfTo1 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SubscriberPayloadDto? SubscriberPayloadDto { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public TopicPayloadDto? TopicPayloadDto { get; set; }

        public TriggerEventRequestDtoToType Type { get; set; }
        public static TriggerEventRequestDtoTo CreateArrayOfTo1(List<To1> arrayOfTo1)
        {
            TriggerEventRequestDtoToType typ = TriggerEventRequestDtoToType.ArrayOfTo1;

            TriggerEventRequestDtoTo res = new TriggerEventRequestDtoTo(typ);
            res.ArrayOfTo1 = arrayOfTo1;
            return res;
        }
        public static TriggerEventRequestDtoTo CreateStr(string str)
        {
            TriggerEventRequestDtoToType typ = TriggerEventRequestDtoToType.Str;

            TriggerEventRequestDtoTo res = new TriggerEventRequestDtoTo(typ);
            res.Str = str;
            return res;
        }
        public static TriggerEventRequestDtoTo CreateSubscriberPayloadDto(SubscriberPayloadDto subscriberPayloadDto)
        {
            TriggerEventRequestDtoToType typ = TriggerEventRequestDtoToType.SubscriberPayloadDto;

            TriggerEventRequestDtoTo res = new TriggerEventRequestDtoTo(typ);
            res.SubscriberPayloadDto = subscriberPayloadDto;
            return res;
        }
        public static TriggerEventRequestDtoTo CreateTopicPayloadDto(TopicPayloadDto topicPayloadDto)
        {
            TriggerEventRequestDtoToType typ = TriggerEventRequestDtoToType.TopicPayloadDto;

            TriggerEventRequestDtoTo res = new TriggerEventRequestDtoTo(typ);
            res.TopicPayloadDto = topicPayloadDto;
            return res;
        }

        public class TriggerEventRequestDtoToConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(TriggerEventRequestDtoTo);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.TopicPayloadDto)
                    {
                        TopicPayloadDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TopicPayloadDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TopicPayloadDto), new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.TopicPayloadDto), "TopicPayloadDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.SubscriberPayloadDto)
                    {
                        SubscriberPayloadDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SubscriberPayloadDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SubscriberPayloadDto), new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.SubscriberPayloadDto), "SubscriberPayloadDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.ArrayOfTo1)
                    {
                        ArrayOfTo1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<To1>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<To1>), new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.ArrayOfTo1), "ArrayOfTo1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new TriggerEventRequestDtoTo(TriggerEventRequestDtoToType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                TriggerEventRequestDtoTo res = (TriggerEventRequestDtoTo)value;

                if (res.ArrayOfTo1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfTo1));
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.SubscriberPayloadDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SubscriberPayloadDto));
                    return;
                }

                if (res.TopicPayloadDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TopicPayloadDto));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}