//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Novu.Models.Components;
    using Novu.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TriggerEventToAllRequestDtoActorType
    {
        private TriggerEventToAllRequestDtoActorType(string value) { Value = value; }

        public string Value { get; private set; }

        public static TriggerEventToAllRequestDtoActorType Str { get { return new TriggerEventToAllRequestDtoActorType("str"); } }

        public static TriggerEventToAllRequestDtoActorType SubscriberPayloadDto { get { return new TriggerEventToAllRequestDtoActorType("SubscriberPayloadDto"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TriggerEventToAllRequestDtoActorType v) { return v.Value; }
        public static TriggerEventToAllRequestDtoActorType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "SubscriberPayloadDto": return SubscriberPayloadDto;
                default: throw new ArgumentException("Invalid value for TriggerEventToAllRequestDtoActorType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TriggerEventToAllRequestDtoActorType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// It is used to display the Avatar of the provided actor's subscriber id or actor object.<br/>
    ///     If a new actor object is provided, we will create a new subscriber in our system.
    /// </summary>
    [JsonConverter(typeof(TriggerEventToAllRequestDtoActor.TriggerEventToAllRequestDtoActorConverter))]
    public class TriggerEventToAllRequestDtoActor
    {
        public TriggerEventToAllRequestDtoActor(TriggerEventToAllRequestDtoActorType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public string? Str { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SubscriberPayloadDto? SubscriberPayloadDto { get; set; }

        public TriggerEventToAllRequestDtoActorType Type { get; set; }
        public static TriggerEventToAllRequestDtoActor CreateStr(string str)
        {
            TriggerEventToAllRequestDtoActorType typ = TriggerEventToAllRequestDtoActorType.Str;

            TriggerEventToAllRequestDtoActor res = new TriggerEventToAllRequestDtoActor(typ);
            res.Str = str;
            return res;
        }
        public static TriggerEventToAllRequestDtoActor CreateSubscriberPayloadDto(SubscriberPayloadDto subscriberPayloadDto)
        {
            TriggerEventToAllRequestDtoActorType typ = TriggerEventToAllRequestDtoActorType.SubscriberPayloadDto;

            TriggerEventToAllRequestDtoActor res = new TriggerEventToAllRequestDtoActor(typ);
            res.SubscriberPayloadDto = subscriberPayloadDto;
            return res;
        }

        public class TriggerEventToAllRequestDtoActorConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(TriggerEventToAllRequestDtoActor);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new TriggerEventToAllRequestDtoActor(TriggerEventToAllRequestDtoActorType.SubscriberPayloadDto)
                    {
                        SubscriberPayloadDto = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SubscriberPayloadDto>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SubscriberPayloadDto), new TriggerEventToAllRequestDtoActor(TriggerEventToAllRequestDtoActorType.SubscriberPayloadDto), "SubscriberPayloadDto"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (json[0] == '"' && json[^1] == '"'){
                    return new TriggerEventToAllRequestDtoActor(TriggerEventToAllRequestDtoActorType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                TriggerEventToAllRequestDtoActor res = (TriggerEventToAllRequestDtoActor)value;

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.SubscriberPayloadDto != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SubscriberPayloadDto));
                    return;
                }
            }

        }

    }
}