//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;

    public class UpdateTopicSubscriptionRequestDto
    {
        /// <summary>
        /// The name of the subscription.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The preferences of the topic. Can be a simple workflow ID string, workflow preference object, or group filter object.
        /// </summary>
        [JsonProperty("preferences")]
        public List<UpdateTopicSubscriptionRequestDtoPreferences>? Preferences { get; set; }
    }
}