//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System.Collections.Generic;

    public class UpdateContextRequestDto
    {
        /// <summary>
        /// Custom data to associate with this context. Replaces existing data.
        /// </summary>
        [JsonProperty("data")]
        public Dictionary<string, object> Data { get; set; } = default!;

        /// <summary>
        /// Optional bridge URL override for agent connect. When an inbound agent turn resolves this context, its bridge call is routed here instead of the agent default bridge URL. Must be a publicly reachable URL. Pass null to clear an existing override.
        /// </summary>
        [JsonProperty("bridgeUrl")]
        public string? BridgeUrl { get; set; } = null;
    }
}