//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Utils;
    using System;

    /// <summary>
    /// Discovery scope of the agent. Always `public` today; reserved for the upcoming private-agents feature.
    /// </summary>
    public enum Visibility
    {
        [JsonProperty("public")]
        Public,
        [JsonProperty("private")]
        Private,
    }

    public static class VisibilityExtension
    {
        public static string Value(this Visibility value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Visibility ToEnum(this string value)
        {
            foreach(var field in typeof(Visibility).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Visibility)
                    {
                        return (Visibility)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Visibility");
        }
    }
}