//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    
    /// <summary>
    /// User who last published the workflow
    /// </summary>
    public class WorkflowListResponseDtoLastPublishedBy
    {

        /// <summary>
        /// User ID
        /// </summary>
        [JsonProperty("_id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// User first name
        /// </summary>
        [JsonProperty("firstName")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// User last name
        /// </summary>
        [JsonProperty("lastName")]
        public WorkflowListResponseDtoLastPublishedByLastName? LastName { get; set; } = null;

        /// <summary>
        /// User external ID
        /// </summary>
        [JsonProperty("externalId")]
        public string? ExternalId { get; set; } = null;
    }
}