//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class WorkflowPreferencesDto
    {

        /// <summary>
        /// A preference for the workflow. The values specified here will be used if no preference is specified for a channel.
        /// </summary>
        [JsonProperty("all", NullValueHandling = NullValueHandling.Include)]
        public All All { get; set; } = default!;

        /// <summary>
        /// Preferences for different communication channels
        /// </summary>
        [JsonProperty("channels")]
        public Dictionary<string, ChannelPreferenceDto> Channels { get; set; } = default!;
    }
}