//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Components
{
    using Newtonsoft.Json;
    using Novu.Models.Components;
    using Novu.Utils;
    using System.Collections.Generic;
    
    public class WorkflowListResponseDto
    {

        /// <summary>
        /// Name of the workflow
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Tags associated with the workflow
        /// </summary>
        [JsonProperty("tags")]
        public List<string>? Tags { get; set; }

        /// <summary>
        /// Last updated timestamp
        /// </summary>
        [JsonProperty("updatedAt")]
        public string UpdatedAt { get; set; } = default!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [JsonProperty("createdAt")]
        public string CreatedAt { get; set; } = default!;

        /// <summary>
        /// Unique database identifier
        /// </summary>
        [JsonProperty("_id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Workflow identifier
        /// </summary>
        [JsonProperty("workflowId")]
        public string WorkflowId { get; set; } = default!;

        /// <summary>
        /// Workflow slug
        /// </summary>
        [JsonProperty("slug")]
        public string Slug { get; set; } = default!;

        /// <summary>
        /// Status of the workflow
        /// </summary>
        [JsonProperty("status")]
        public WorkflowStatusEnum Status { get; set; } = default!;

        /// <summary>
        /// Origin of the workflow
        /// </summary>
        [JsonProperty("origin")]
        public WorkflowOriginEnum Origin { get; set; } = default!;

        /// <summary>
        /// Timestamp of the last workflow trigger
        /// </summary>
        [JsonProperty("lastTriggeredAt")]
        public string? LastTriggeredAt { get; set; } = null;

        /// <summary>
        /// Overview of step types in the workflow
        /// </summary>
        [JsonProperty("stepTypeOverviews")]
        public List<StepTypeEnum> StepTypeOverviews { get; set; } = default!;
    }
}