//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Requests
{
    using Novu.Utils;
    
    public class EventsControllerCancelRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=transactionId")]
        public string TransactionId { get; set; } = default!;

        /// <summary>
        /// A header for idempotency purposes
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }
    }
}