//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Requests
{
    using Novu.Models.Components;
    using Novu.Utils;

    public class LayoutsControllerListRequest
    {
        /// <summary>
        /// Number of items to return per page.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public double? Limit { get; set; }

        /// <summary>
        /// Number of items to skip before starting to return results.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")]
        public double? Offset { get; set; }

        /// <summary>
        /// Direction of sorting.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderDirection")]
        public DirectionEnum? OrderDirection { get; set; }

        /// <summary>
        /// Field to sort the results by.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderBy")]
        public LayoutResponseDtoSortField? OrderBy { get; set; }

        /// <summary>
        /// Search query to filter layouts.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=query")]
        public string? Query { get; set; }

        /// <summary>
        /// A header for idempotency purposes.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }
    }
}