//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Novu.Models.Requests
{
    using Novu.Utils;

    public class TranslationControllerGetMasterJsonEndpointRequest
    {
        /// <summary>
        /// Locale to export. If not provided, exports organization default locale.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=locale")]
        public string? Locale { get; set; }

        /// <summary>
        /// A header for idempotency purposes.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")]
        public string? IdempotencyKey { get; set; }
    }
}