workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Novu API:
        inputs:
            - location: https://api.novu.co/openapi.sdk.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/speakeasy-errorissue-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/novu/novu/novu-api-csharp
targets:
    novu:
        target: csharp
        source: Novu API
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/novu/novu/novu-api-csharp-code-samples
            labelOverride:
                fixedValue: Csharp (SDK)
            blocking: false
